name: sft-eplantation-back-test
on: 
  push:
    branches:
      - main

permissions:
      id-token: write
      contents: read
      
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        # working-directory: Sketec.UI
        run: docker build . --file Api.Dockerfile 
